### ISSUE TITLE
php7.4

### ISSUE THREAD

**Issue by nunofmmarques** [RVxLab/filament-colorpicker#1]
Hi!

I'm currently using filament on a project and this colorpicker of yours would be really handy!
The thing is that i'm using php7.4 and i cant use php8 for multiple reasons, but i would really used your package.

Any tip on how i can use it on php7.4?

Thank you!

**Comment by RVxLab** [comment]
With PHP 7.4 being in maintenance mode soon and going EOL next year I have no intention of supporting it. 

If you need to work with 7.4 I recommend forking it and adding it in yourself. Most of the code is tested and the package is small so that shouldn’t be too hard.

If you don’t mind me asking, why can’t you upgrade to 8.0?
